// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.policies.applied", true);
user_pref("browser.region.update.updated", 1753200324);
user_pref("browser.search.region", "CO");
user_pref("calendar.caldav.googleResync", 1753200323);
user_pref("calendar.list.sortOrder", "72051a3f-f5d8-4802-b353-4ee9dacdd775");
user_pref("calendar.registry.72051a3f-f5d8-4802-b353-4ee9dacdd775.calendar-main-default", true);
user_pref("calendar.registry.72051a3f-f5d8-4802-b353-4ee9dacdd775.calendar-main-in-composite", true);
user_pref("calendar.registry.72051a3f-f5d8-4802-b353-4ee9dacdd775.disabled", true);
user_pref("calendar.registry.72051a3f-f5d8-4802-b353-4ee9dacdd775.name", "Casa");
user_pref("calendar.registry.72051a3f-f5d8-4802-b353-4ee9dacdd775.type", "storage");
user_pref("calendar.registry.72051a3f-f5d8-4802-b353-4ee9dacdd775.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/Bogota");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1753200333402");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1753200322);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.installedDistroAddon.langpack-en-CA@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-GB@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-US@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-es-AR@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-es-ES@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-es-MX@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20250627203320");
user_pref("extensions.lastAppVersion", "128.12.0");
user_pref("extensions.lastPlatformVersion", "128.12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"9b19eea1-5d19-486d-ba81-7e99b0394e59\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.ui-rdf.version", 46);
user_pref("mailnews.database.global.datastore.id", "c4699554-b092-4393-abea-c19e97760d1");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.12.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1753200319);
user_pref("toolkit.telemetry.cachedClientID", "9f6b5f74-04b7-40a4-a78e-a9e2de258e94");
user_pref("toolkit.telemetry.previousBuildID", "20250627203320");
