# Generated by Django 4.2.11 on 2025-07-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_proyecto_descripcion_en_proyecto_tecnologias_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion_en',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tecnologias_en',
        ),
    ]
